
honeycomb:
  # Specify either your apiKey, **OR** the  name of an existingSecret resource containing your Honeycomb API key
  # apiKey: YOUR_API_KEY
  # existingSecret: honeycomb-api-key

  # Specify host URL to send all events to
  apiHost: api.honeycomb.io:443
  # Specify the name of the dataset to send data to
  dataset: microservices-demo

config:
  processors:
    k8sattributes:
      passthrough: false
      auth_type: "kubeConfig"
      extract:
        metadata:
          # extract the following well-known metadata fields
          - k8s.pod.name
          - k8s.pod.uid
          - k8s.deployment.name
          - k8s.namespace.name
          - k8s.node.name
          - k8s.pod.start_time
  service:
    extensions: [health_check]
    pipelines:
      traces:
        receivers: [otlp]
        processors: [memory_limiter, batch, k8sattributes]
        exporters: [otlp]

# disable ports that are not required
ports:
  jaeger-binary:
    enabled: false
  jaeger-compact:
    enabled: false
  jaeger-grpc:
    enabled: false
  jaeger-http:
    enabled: false
  zipkin:
    enabled: false

k8sProcessor:
  rbac:
    name: "microservices-tagger"
    create: true

serviceAccount:
  create: true

resources:
  limits:
    cpu: 500m
    memory: 2Gi
  requests:
    cpu: 200m
    memory: 400Mi