mode: deployment

replicaCount: 1

presets:
  kubernetesAttributes:
    enabled: true

resources:
  limits:
    cpu: 500m
    memory: 2Gi
  requests:
    cpu: 200m
    memory: 400Mi

config:
  receivers:
    jaeger: null
    zipkin: null
    prometheus: null

  processors:
    filter/analyze-scenario-only:
      error_mode: ignore
      traces:
        span:
          - 'name == "audit start"'
          - 'name == "msdemo.ShippingService/AuditShippingService"'
          - 'name == "msdemo.CheckoutService/AuditCheckoutService"'
          - 'name == "msdemo.ProductCatalogService/AuditProductService"'
          - 'name == "msdemo.StorageService/SaveAudit"'
          - 'name == "INSERT audit transaction"'
    filter/k8s-scenario-only:
      error_mode: ignore
      traces:
        span:
          - |
            name != "audit start" and
            name != "msdemo.ShippingService/AuditShippingService" and
            name != "msdemo.CheckoutService/AuditCheckoutService" and
            name != "msdemo.ProductCatalogService/AuditProductService" and
            name != "msdemo.StorageService/SaveAudit" and
            name != "INSERT audit transaction"

  exporters:
    otlp/prod-analyze:
      endpoint: api.honeycomb.io:443
      headers:
        "x-honeycomb-team": "${HONEYCOMB_API_KEY}"
        "x-honeycomb-dataset": "microservices-metrics"
    otlp/dogfood-analyze:
      endpoint: api-dogfood.honeycomb.io:443
      headers:
        "x-honeycomb-team": "${HONEYCOMB_DOGFOOD_API_KEY}"
        "x-honeycomb-dataset": "microservices-metrics"
    otlp/dogfood-k8s:
      endpoint: api-dogfood.honeycomb.io:443
      headers:
        "x-honeycomb-team": "${HONEYCOMB_DOGFOOD_K8S_API_KEY}"
        "x-honeycomb-dataset": "microservices-metrics"

  service:
    pipelines:
      traces:
        receivers:
          - otlp
        processors:
          - memory_limiter
          - filter/analyze-scenario-only
          - k8sattributes
          - batch
        exporters:
          - otlp/prod-analyze
          - otlp/dogfood-analyze
          - logging
      traces/k8s-scenario:
        receivers:
          - otlp
        processors:
          - memory_limiter
          - filter/k8s-scenario-only
          - k8sattributes
          - batch
        exporters:
          - otlp/dogfood-k8s
          - logging
      metrics:
        receivers:
          - otlp
        exporters:
          - otlp/prod-analyze
          - otlp/dogfood-analyze
          - logging
      logs: null

extraEnvs:
  - name: HONEYCOMB_API_KEY
    valueFrom:
      secretKeyRef:
        key: api-key
        name: honeycomb-opentelemetry-collector
  - name: HONEYCOMB_DOGFOOD_API_KEY
    valueFrom:
      secretKeyRef:
        key: api-key
        name: honeycomb-dogfood-opentelemetry-collector
  - name: HONEYCOMB_DOGFOOD_K8S_API_KEY
    valueFrom:
      secretKeyRef:
        key: api-key
        name: honeycomb-dogfood-k8s-opentelemetry-collector

ports:
  jaeger-compact:
    enabled: false
  jaeger-binary:
    enabled: false
  jaeger-grpc:
    enabled: false
  jaeger-http:
    enabled: false
  zipkin:
    enabled: false
