apiVersion: apps/v1
kind: Deployment
metadata:
  name: adservice
spec:
  selector:
    matchLabels:
      app: adservice
  template:
    metadata:
      labels:
        app: adservice
    spec:
      serviceAccountName: default
      terminationGracePeriodSeconds: 5
      containers:
      - name: server
        image: adservice
        ports:
        - containerPort: 9555
        env:
        - name: OTEL_PROPAGATORS
          value: b3,b3multi,tracecontext,baggage
        - name: PORT
          value: "9555"
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: HONEYCOMB_API_ENDPOINT
          value: http://opentelemetry-collector:4317
        - name: HONEYCOMB_METRICS_DATASET
          value: microservices-metrics
        - name: SERVICE_NAME
          value: adservice
        - name: OTEL_RESOURCE_ATTRIBUTES
          value: ip=$(POD_IP)
        resources:
          requests:
            cpu: 250m
            memory: 180Mi
          limits:
            cpu: 500m
            memory: 300Mi
---
apiVersion: v1
kind: Service
metadata:
  name: adservice
spec:
  type: ClusterIP
  selector:
    app: adservice
  ports:
  - name: grpc
    port: 9555
    targetPort: 9555
