apiVersion: apps/v1
kind: Deployment
metadata:
  name: paymentservice
spec:
  selector:
    matchLabels:
      app: paymentservice
  template:
    metadata:
      labels:
        app: paymentservice
    spec:
      serviceAccountName: default
      terminationGracePeriodSeconds: 5
      containers:
      - name: server
        image: paymentservice
        ports:
        - containerPort: 50051
        env:
        - name: OTEL_PROPAGATORS
          value: b3,b3multi,tracecontext,baggage
        - name: PORT
          value: "50051"
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: grpc://opentelemetry-collector:4317
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: SERVICE_NAME
          value: payment
        #Bug in Nodejs picking up resource attributes https://github.com/open-telemetry/opentelemetry-js/issues/2259
        - name: OTEL_RESOURCE_ATTRIBUTES
          value: service.name=payment,ip=$(POD_IP)
        # readinessProbe:
        #   exec:
        #     command: ["/bin/grpc_health_probe", "-addr=:50051"]
        # livenessProbe:
        #   exec:
        #     command: ["/bin/grpc_health_probe", "-addr=:50051"]
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: paymentservice
spec:
  type: ClusterIP
  selector:
    app: paymentservice
  ports:
  - name: grpc
    port: 50051
    targetPort: 50051
