apiVersion: apps/v1
kind: Deployment
metadata:
  name: shippingservice
spec:
  selector:
    matchLabels:
      app: shippingservice
  template:
    metadata:
      labels:
        app: shippingservice
    spec:
      serviceAccountName: default
      containers:
      - name: server
        image: shippingservice
        ports:
        - containerPort: 50051
        env:
        - name: PORT
          value: "50051"
        # if the tracking-lambda-url key is not found in the secret, this will use the embedded TrackingID generator instead
        - name: TRACKING_LAMBDA_URL
          valueFrom:
            secretKeyRef:
              name: honeycomb
              key: tracking-lambda-url
              optional: true
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: opentelemetry-collector:4317
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: OTEL_RESOURCE_ATTRIBUTES
          value: ip=$(POD_IP)
        # readinessProbe:
        #   periodSeconds: 5
        #   exec:
        #     command: ["/bin/grpc_health_probe", "-addr=:50051"]
        # livenessProbe:
        #   exec:
        #     command: ["/bin/grpc_health_probe", "-addr=:50051"]
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: shippingservice
spec:
  type: ClusterIP
  selector:
    app: shippingservice
  ports:
  - name: grpc
    port: 50051
    targetPort: 50051
